# Numpy

### NumPy, short for Numerical Python, is one of the most important foundational packages for numerical computing in Python


In [1]:
import numpy as np 

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%timeit my_arr2 = my_arr * 2

8.54 ms ± 519 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
%timeit my_list2 =[ x*2 for x in my_list] # to show how fast numpy is compared to pythons in buit loop

144 ms ± 31.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### ndarray: A powerful n-dimensional array object that allows for efficient storage and manipulation of large datasets.

In [5]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [6]:
data*10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [7]:
data+data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.empty((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### Table 4-1. Some important NumPy array creation functions

| Function | Description |
| :--- | :--- |
| `array` | Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a data type or explicitly specifying a data type; copies the input data by default |
| `asarray` | Convert input to ndarray, but do not copy if the input is already an ndarray |
| `arange` | Like the built-in range but returns an ndarray instead of a list |
| `ones`, `ones_like` | Produce an array of all 1s with the given shape and data type; `ones_like` takes another array and produces a ones array of the same shape and data type |
| `zeros`, `zeros_like` | Like `ones` and `ones_like` but producing arrays of 0s instead |
| | |
| `empty`, `empty_like` | Create new arrays by allocating new memory, but do not populate with any values like ones and zeros |
| `full`, `full_like` | Produce an array of the given shape and data type with all values set to the indicated "fill value"; `full_like` takes another array and produces a filled array of the same shape and data type |
| `eye`, `identity` | Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere) |