In [1]:
import numpy as np

### Pseudorandom Number Generation

In [2]:
samples = np.random.standard_normal(size=(4,4))
samples

array([[ 0.05007197, -0.92708603,  0.26747264, -0.33044239],
       [ 1.88460449, -0.94213691, -0.12705093, -0.4724145 ],
       [-0.84994316, -0.06542635,  0.87216505, -0.05897009],
       [-0.96648732,  0.80529378, -0.36280089,  0.3728473 ]])

In [3]:
rng = np.random.default_rng(seed = 12345)
data = rng.standard_normal(size=(3,3))
data

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 ,  0.36105811]])

### Universal Functions: Fast Element-Wise Array Functions

In [4]:
arr = np.arange(10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
x = rng.standard_normal(8)
y = rng.standard_normal(8)

np.maximum(x,y)

array([-1.25666813,  2.34740965,  1.39897899,  1.32229806,  0.90219827,
        0.90291934, -0.06068952,  0.78884434])

In [6]:
arr = rng.standard_normal(5)*5
arr

array([ 2.24741966, -6.71800536, -0.40843795,  8.62369966, 13.09079713])

In [7]:
remainder,whole_part = np.modf(arr)

In [8]:
remainder

array([ 0.24741966, -0.71800536, -0.40843795,  0.62369966,  0.09079713])

In [9]:
whole_part

array([ 2., -6., -0.,  8., 13.])

In [10]:
np.add(arr,1, out = arr) # for the use of out this efficiently uses memory rather than using another chunk of memory 

array([ 3.24741966, -5.71800536,  0.59156205,  9.62369966, 14.09079713])

### Some unary universal functions

| Function | Description |
| :--- | :--- |
| `abs`, `fabs` | Compute the absolute value element-wise for integer, floating-point, or complex values |
| `sqrt` | Compute the square root of each element (equivalent to `arr ** 0.5`) |
| `square` | Compute the square of each element (equivalent to `arr ** 2`) |
| `exp` | Compute the exponent $e^x$ of each element |
| `log`, `log10`, `log2`, `log1p` | Natural logarithm (base $e$), log base 10, log base 2, and $\log(1 + x)$, respectively |
| `sign` | Compute the sign of each element: 1 (positive), 0 (zero), or -1 (negative) |
| `ceil` | Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that number) |
| `floor` | Compute the floor of each element (i.e., the largest integer less than or equal to each element) |
| `rint` | Round elements to the nearest integer, preserving the dtype |
| `modf` | Return fractional and integral parts of array as separate arrays |
| `isnan` | Return Boolean array indicating whether each value is NaN (Not a Number) |
| `isfinite`, `isinf` | Return Boolean array indicating whether each element is finite (non-inf, non-NaN) or infinite, respectively |
| `cos`, `cosh`, `sin`, `sinh`, `tan`, `tanh` | Regular and hyperbolic trigonometric functions |
| `arccos`, `arccosh`, `arcsin`, `arcsinh`, `arctan`, `arctanh` | Inverse trigonometric functions |
| `logical_not` | Compute truth value of not x element-wise (equivalent to `~arr`) |

### Some binary universal functions

| Function | Description |
| :--- | :--- |
| `add` | Add corresponding elements in arrays |
| `subtract` | Subtract elements in second array from first array |
| `multiply` | Multiply array elements |
| `divide`, `floor_divide` | Divide or floor divide (truncating the remainder) |
| `power` | Raise elements in first array to powers indicated in second array |
| `maximum`, `fmax` | Element-wise maximum; `fmax` ignores NaN |
| `minimum`, `fmin` | Element-wise minimum; `fmin` ignores NaN |
| `mod` | Element-wise modulus (remainder of division) |
| `copysign` | Copy sign of values in second argument to values in first argument |
| `greater`, `greater_equal`, `less`, `less_equal`, `equal`, `not_equal` | Perform element-wise comparison, yielding Boolean array (equivalent to infix operators `>`, `>=`, `<`, `<=`, `==`, `!=`) |
| `logical_and` | Compute element-wise truth value of AND (&) logical operation |
| `logical_or` | Compute element-wise truth value of OR (\|) logical operation |
| `logical_xor` | Compute element-wise truth value of XOR (^) logical operation |